import Head from "next/head";
import Image from "next/image";
import { EN } from "../locales/en";
import { NL } from "../locales/nl";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  const { locale } = router;

  const translation = locale === "en" ? EN : NL;

  const changeLanguage = (event: { target: { value: any } }) => {
    const locale = event.target.value;
    router.push("/", "/", { locale });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <select onChange={changeLanguage} defaultValue={locale}>
          <option value="en">EN</option>
          <option value="nl">NL</option>
        </select>
        <h2>{translation.title}</h2>
        <p>{translation.subTitle}</p>
      </main>
    </div>
  );
}
